targets:
  centos-6:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  centos-7:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel

before:
  - uname -a
  - ruby -v
  - env
  - echo "gem 'pg'" >> Gemfile.local
  - cp config/database.yml.pkgr config/database.yml

after:
  - ruby -v
  - #after

before_install:
  - ruby -v
  - #before_install
  - bundle install

after_install:
  - ruby -v
  - #after_install

env:
  - RAILS_ENV=production
  - PORT=3000
  - RAILS_SERVE_STATIC_FILES=true

notifications: false
