targets:
  centos-6:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  centos-7:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel

before:
  - uname -a
  - env
  - echo "gem 'pg'" >> Gemfile.local

env:
  - RAILS_ENV=production
  - PORT=3000
  - RAILS_SERVE_STATIC_FILES=true

notifications: false
